### PR TITLE
Catch MalformedURLException in HttpDataManager and re-throw a RuntimeException

### PR DESCRIPTION
**Pull request by rosshamish**
Add HttpDataManagerInitializationException (Runtime), throw that on MalformedURLException

This is in contrast to the current approach: marking methods as `throws MalformedURLException`, and letting the MalformedURLException bubble up the stack into models and controllers.

Once we aren't in HttpDataManager anymore, the MalformedURLException becomes less useful, since it's only relevant to the HttpDataManager. Also, the URL to elasticsearch is a hard-coded string, so if it throws MalformedURL, something is very wrong and we should abort.

HttpDataManagerInitializationException is a RuntimeException, so it doesn't need to be caught, it will just halt the application immediately.

### CODE REVIEW

**Comment by MEGASTACK** [comment]
Check the CI results, you goofed on naming the class

**Comment by MEGASTACK** [comment]
Other then that I support this idea.

**Comment by MEGASTACK** [comment]
Goofed again - are the builds halting on first failure? Maybe should we change that?

Maybe you should run ./gradlew connectedAndroidTest before pushing? (it will be faster then waiting for travis)

**Comment by kyleoshaughnessy** [comment]
i like it

**Comment by udeyrishi** [comment]
I would rather leave the HttpDataManager as is, because it is using the language feature "throws" to expose out the behaviour. 
I agree with the fact that MalformedUrlException is only applicable to HttpDataManager, and when we swap it out with another DataManager, it won't be applicable anymore. So, ideally, this should be addresses in another way by which a standard injector injects the appropriate DataManager (the one currently being used) into all the clients of the DataManager. A factory, perhaps? The factory takes care of handling the exception once, and the clients don't have to worry about it. This way, we will remove the nastiness in all the clients, but we will be explicitly stating that MalformedUrlException needs to be handled, because the current version of DataManager being used is the Http one. 

As far as the hardcoded URL is concerned, it is a valid URL, and it won't ever throw an exception. The only time MalformedUrlException is thrown is when it tries to append dataKey.toString() to the end of the root (hardcoded) URL. Now if the URL doesn't match the criteria used by standard URLs, we want the exception to be thrown.

**Comment by MEGASTACK** [comment]
Probably the real solution is to have DataManager as a class (rather than interface?), which then delegates to the more specific DataManagers (http, local, ...). IE, proxy pattern.

**Comment by udeyrishi** [comment]
We are using proxy pattern in QueuedDataManafer which will be delegating the duties in the way you described. Using an interface allows there to be standard interface, and parallel development while it is still being developed (as we are doing right now).

**Comment by rosshamish** [comment]
@udeyrishi So when QueuedDataManager exists, it will handle this MalformedURLException? Or will it still bubble up to the classes which use the QueuedDataManager?

**Comment by MEGASTACK** [comment]
Remember that a catch block for an exception that is not thrown is a compile error - If we don't fix this now, and the proxy Queued handles the exception, its going to be a bit of a pain to change later.

**Comment by udeyrishi** [comment]
It will still bubble up, because of the same reasons as CachedDataManager. A bad URL is a bad URL. However, the factory that I'm proposing will mask it out as a runtime exception.

I'm not concerned either way, because at the end of the day we are still masking the exception as a runtime one. It's only a matter of clean software design where each class is more or less exposing its APIs to the clients, not knowing who these clients will be. This API includes the potential non-runtime exceptions. Less coupling == better design. If we want to do this masking, we do it explicitly via an adapter of some sort (the factory). That's my 2 cents. 

For the purposes of this app, this is me more or less nit-picking. Feel free to ignore what I'm saying :-)

**Comment by udeyrishi** [comment]
Never mind. I take back everything I said. I got confused as to what the source of the MalformedURLException is. You're right, it's the hardcoded root URL. Feel free to ignore all my jibber-jabber above, and go forward with the merge.

**Pull request merged**
